"""empty message

Revision ID: 110892687be8
Revises: None
Create Date: 2014-05-07 20:30:53.149597

"""

# revision identifiers, used by Alembic.
revision = '110892687be8'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), server_default='now()', autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=u'messages_pk')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default="nextval('user_user_id_seq'::regclass)", nullable=False),
    sa.Column('username', sa.CHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('datetime_created', postgresql.TIMESTAMP(timezone=True), server_default='now()', autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=u'pk_users')
    )
    ### end Alembic commands ###
